---
- name: "Deploy models to endpoints"
  hosts: localhost
  gather_facts: false
  tasks:

    - name: Deploy Upload Data
      shell: |
        gcloud compute instances create-with-container ansible-data \
          --project='secret-cipher-399620' \
          --zone='us-east1-a' \
          --machine-type='e2-medium' \
          --service-account='data-service-account@secret-cipher-399620.iam.gserviceaccount.com' \
          --tags=http-server,https-server \
          --container-image="gcr.io/secret-cipher-399620/custom-upload-data-ansible:latest" 
      async: 999999
      poll: 0

    - name: Deploy Upload Model
      shell: |
        gcloud compute instances create-with-container ansible-model \
          --project='secret-cipher-399620' \
          --zone='us-east1-a' \
          --machine-type='e2-medium' \
          --service-account='data-service-account@secret-cipher-399620.iam.gserviceaccount.com' \
          --tags=http-server,https-server \
          --container-image="gcr.io/secret-cipher-399620/custom-upload-model-ansible:latest" 
      async: 999999
      poll: 0
