---
- name: "Build docker images and push them to GCR"
  hosts: localhost
  gather_facts: false
  tasks:
  - name: "Get timestamp for docker tag"
    shell: "(date +%Y%m%d%H%M%S)"
    register: tag
  - name: Print tag
    debug:
      var: tag
  - name: Build custom-upload-data container image
    community.general.docker_image:
      build:
        path: ../custom_upload_data
      name: gcr.io/{{ gcp_project }}/custom-upload-data-ansible:{{ tag.stdout}}
      source: build
  - name: Push custom-upload-data image to GCR
    community.general.docker_image:
      name: gcr.io/{{ gcp_project }}/custom-upload-data-ansible:{{ tag.stdout}}
      repository: gcr.io/{{ gcp_project }}/custom-upload-data-ansible:{{ tag.stdout}}
      push: yes
      source: local
  - name: Build custom-upload-model container image
    community.general.docker_image:
      build:
        path: ../custom_upload_model
      name: gcr.io/{{ gcp_project }}/custom-upload-model-ansible:{{ tag.stdout}}
      source: build
  - name: Push custom-upload-model image to GCR
    community.general.docker_image:
      name: gcr.io/{{ gcp_project }}/custom-upload-model-ansible:{{ tag.stdout}}
      repository: gcr.io/{{ gcp_project }}/custom-upload-model-ansible:{{ tag.stdout}}
      push: yes
      source: local
  - name: "Save docker tag"
    shell: echo {{ tag.stdout}} > .docker-tag