---
- name: "Build docker images and push them to Docker Hub"
  hosts: localhost
  gather_facts: false
  tasks:
    - name: "Get timestamp for docker tag"
      shell: "(date +%Y%m%d%H%M%S)"
      register: tag

    - name: Print tag
      debug:
        var: tag.stdout

    - name: Log in to Docker Hub
      community.general.docker_login:
        username:  ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

    - name: Build frontend container image
      community.general.docker_image:
        build:
          path: ../app-building
        name: " ${{ secrets.DOCKERHUB_USERNAME }}/frontend-ansible:{{ tag.stdout }}"
        source: build

    - name: Push frontend image to Docker Hub
      community.general.docker_image:
        name: " ${{ secrets.DOCKERHUB_USERNAME }}/frontend-ansible:{{ tag.stdout }}"
        push: yes
        source: local
    - name: "Save docker tag"
      shell: echo {{ tag.stdout}} > .docker-tag
