---
- name: "Deploy models to endpoints"
  hosts: localhost
  gather_facts: false
  tasks:
    
    - name: Deploy Frontend with Startup Script
      shell: |
        # Enable all required Google Cloud APIs
        gcloud services enable compute.googleapis.com containerregistry.googleapis.com \
          --project='secret-cipher-399620'
        
        # Create the VM with the startup script
        gcloud compute instances create frontend-m6 \
          --project='secret-cipher-399620' \
          --zone='us-east4-a' \
          --machine-type='e2-medium' \
          --service-account='frontend-account@secret-cipher-399620.iam.gserviceaccount.com' \
          --tags=http-server,https-server \
          --scopes='https://www.googleapis.com/auth/cloud-platform' \
          --metadata startup-script='#!/bin/bash
          sudo apt-get update
          sudo apt-get install -y docker.io
          sudo systemctl start docker
          sudo docker pull elijahdabkowski/frontend:0.3
          sudo docker run --restart=always -d -p 3000:3000 -p 3001:3001 elijahdabkowski/frontend:0.3'
      async: 999999
      poll: 0




